"""
P5-09 | compare_models.py
Compare Logistic Regression baseline vs XGBoost across CV folds.

MOCK DATA NOTE:
  If results JSON files do not exist, synthetic results are generated
  to allow the script to run standalone.
"""

import sys
sys.stdout.reconfigure(encoding='utf-8')

import json
import numpy as np
from pathlib import Path

BASE = Path(r'/Users/lelinh/Documents/BBKH')
BASELINE_JSON = BASE / 'P5-07' / 'baseline_results.json'
XGB_JSON      = BASE / 'P5-08' / 'xgb_results.json'
OUTPUT_MD     = BASE / 'P5-09' / 'model_comparison.md'


# ---------------------------------------------------------------------------
MOCK_BASELINE = {
    'model': 'LogisticRegression_baseline (MOCK)',
    'avg': {'recall': 0.52, 'precision': 0.38, 'f1': 0.44, 'auc': 0.71},
    'folds': [
        {'fold': i+1, 'recall': round(0.52+np.random.uniform(-0.05,0.05),4),
         'precision': round(0.38+np.random.uniform(-0.05,0.05),4),
         'f1': round(0.44+np.random.uniform(-0.05,0.05),4),
         'auc': round(0.71+np.random.uniform(-0.03,0.03),4)}
        for i in range(5)
    ],
}
MOCK_XGB = {
    'model': 'XGBoost (MOCK)',
    'avg': {'recall': 0.68, 'precision': 0.51, 'f1': 0.58, 'auc': 0.81},
    'folds': [
        {'fold': i+1, 'recall': round(0.68+np.random.uniform(-0.05,0.05),4),
         'precision': round(0.51+np.random.uniform(-0.05,0.05),4),
         'f1': round(0.58+np.random.uniform(-0.05,0.05),4),
         'auc': round(0.81+np.random.uniform(-0.03,0.03),4)}
        for i in range(5)
    ],
}


def load_results(path: Path, mock_data: dict) -> dict:
    if path.exists():
        with open(path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        print(f"Loaded: {path}")
        return data
    else:
        print(f"[WARN] {path} not found — using mock results.")
        return mock_data


def fmt(v):
    if v is None:
        return 'N/A'
    return f'{float(v):.4f}'


# ---------------------------------------------------------------------------
def build_comparison_table(bl: dict, xgb: dict) -> str:
    lines = []
    lines.append("# Model Comparison: Logistic Regression Baseline vs XGBoost\n")
    lines.append(f"> **Baseline model**: {bl.get('model', 'LogisticRegression_baseline')}")
    lines.append(f"> **Main model**: {xgb.get('model', 'XGBoost')}")
    if xgb.get('nlp_features_mock'):
        lines.append("> **NOTE**: NLP features (8-10) are MOCK — replace with P3-12 output\n")
    lines.append("")

    # Per-fold table
    lines.append("## Per-Fold Results\n")
    header = "| Fold | BL Recall | BL Prec | BL F1 | BL AUC | XGB Recall | XGB Prec | XGB F1 | XGB AUC |"
    sep    = "|------|-----------|---------|-------|--------|------------|----------|--------|---------|"
    lines.append(header)
    lines.append(sep)

    bl_folds  = {f['fold']: f for f in bl.get('folds', [])}
    xgb_folds = {f['fold']: f for f in xgb.get('folds', [])}

    for fold_n in sorted(set(list(bl_folds.keys()) + list(xgb_folds.keys()))):
        bf  = bl_folds.get(fold_n, {})
        xf  = xgb_folds.get(fold_n, {})
        lines.append(
            f"| {fold_n} "
            f"| {fmt(bf.get('recall'))} | {fmt(bf.get('precision'))} "
            f"| {fmt(bf.get('f1'))} | {fmt(bf.get('auc'))} "
            f"| {fmt(xf.get('recall'))} | {fmt(xf.get('precision'))} "
            f"| {fmt(xf.get('f1'))} | {fmt(xf.get('auc'))} |"
        )

    # Average row
    ba  = bl.get('avg', {})
    xa  = xgb.get('avg', {})
    lines.append(
        f"| **AVG** "
        f"| **{fmt(ba.get('recall'))}** | **{fmt(ba.get('precision'))}** "
        f"| **{fmt(ba.get('f1'))}** | **{fmt(ba.get('auc'))}** "
        f"| **{fmt(xa.get('recall'))}** | **{fmt(xa.get('precision'))}** "
        f"| **{fmt(xa.get('f1'))}** | **{fmt(xa.get('auc'))}** |"
    )

    # Delta
    lines.append("")
    lines.append("## Delta (XGBoost − Baseline)\n")
    lines.append("| Metric | Baseline AVG | XGBoost AVG | Delta |")
    lines.append("|--------|-------------|-------------|-------|")
    for metric in ['recall', 'precision', 'f1', 'auc']:
        bv = ba.get(metric)
        xv = xa.get(metric)
        if bv is not None and xv is not None:
            delta = float(xv) - float(bv)
            sign  = '+' if delta >= 0 else ''
            lines.append(f"| {metric.upper()} | {fmt(bv)} | {fmt(xv)} | {sign}{delta:.4f} |")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by P5-09/compare_models.py*")
    return '\n'.join(lines)


# ---------------------------------------------------------------------------
if __name__ == '__main__':
    print("=== P5-09 Model Comparison ===\n")

    np.random.seed(0)
    bl  = load_results(BASELINE_JSON, MOCK_BASELINE)
    xgb = load_results(XGB_JSON, MOCK_XGB)

    table_md = build_comparison_table(bl, xgb)
    print("\n" + table_md)

    OUTPUT_MD.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_MD, 'w', encoding='utf-8') as f:
        f.write(table_md)
    print(f"\nComparison table saved → {OUTPUT_MD}")
    print("\nP5-09 OK")
